### ISSUE TITLE
Need documentation on how to flash new .hex file

### ISSUE THREAD

**Issue by jedimatt42** [MonsterJoysticks/9-Pin-Joystick-to-USB-Adapter#1]
The makefile has some hints... but I can't tell what the intentions are. 

I assume, with the correct connection to a pc, make flash does the trick... however...

There is a flash switch on the device, without clear indication which position it should be in. 
There is a usb port for the device to be a HID controller, and there are unpopulated JTEG (maybe?) pins for in system programming... 

Will the device program over the onboard USB connector? or does it need a usb programming cable such as a JTDI cable? 

A little clarification in the README.md would be great!

I need to reprogram it, to work with my sega 6 button devices. The firmware doesn't detect the 8bitdo M30 2.4g controller, and holding down the start button isn't an option.

**Comment by jedimatt42** [comment]
Ok, I plugged the usb cable in, and measured the PROG port to figure out where VCC and GND are. And was then able to use my USBtinyISP programmer with avrdude to reprogram the adapter.

I still don't know what the 'flash' switch does.

```
---pcb-edge-------------------
         o o o
  GND->  o o o <- VCC

            CRYSTAL
```

**Comment by MonsterJoysticks** [comment]
We do indeed need to flesh out the readme file and you are the first person so far to have shown any interest in updating the firmware. 

The device has the BootloadHID boot loader flashed to the first 2Kb https://www.obdev.at/products/vusb/bootloadhid.html <https://www.obdev.at/products/vusb/bootloadhid.html> so when you move the switch to the position closest to the 9 pin connector the device will start into the boot loader where you can use their command line tool to update the remaining 6Kb of flash space with your complied hex file.

There is a JTAG connector on the board and it is used to flash the initial boot loader onto the device and then the firmware is flashed via USB.

**Comment by MonsterJoysticks** [comment]
I have updated the README.md file with some instructions on how to flash new firmware to the device.
