### ISSUE TITLE
A500 Mini support

### ISSUE THREAD

**Issue by LakesGeek** [MonsterJoysticks/9-Pin-Joystick-to-USB-Adapter#5]
Pretty please :)

Always willing to help test 

(currently does Nothing)

**Comment by 5StringsOfDoom** [comment]
I Have forked the code and i'm trying out various changes to see if the device can be used on the A500 Mini.

**Comment by MonsterJoysticks** [comment]
I have released a guide on how to modify the A500 to accept our adapter and probably any unsupported Joystick or Gamepad https://monsterjoysticks.com/support/a500-mini-9-pin-joystick-to-usb-adapter-guide
